name: gonzalolopez_webpage
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/avenir-next/avenir-next-regular.ttf
          weight: 400
        - asset: assets/fonts/avenir-next/avenir-next-medium.ttf
          weight: 500
        - asset: assets/fonts/avenir-next/avenir-next-demi.ttf
          weight: 600
        - asset: assets/fonts/avenir-next/avenir-next-bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/montserrat-regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/montserrat-medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/montserrat-bold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/montserrat-black.ttf
          weight: 700
    - family: Kaushanscript
      fonts:
        - asset: assets/fonts/kaushanscript-regular.ttf
          weight: 400
